### PR TITLE
New post about summer school

### PR DESCRIPTION
**Pull request by Mymoza**
Let me know if that's the kind of posts you were expecting? :)

### CODE REVIEW

**Comment by hbredin** [comment]
Is there somewhere we can see it rendered? 
Or do we have to be fluent in markdown? (I am, don't worry ;))

**Comment by Mymoza** [comment]
I think we can only see it rendered once it's merged... Except if you clone this repo locally and get Jekyll started and execute the website locally... 🤔

**Comment by Mymoza** [comment]
[JSALT Summer School _ Speaker Detection in Adverse Scenarios with a Single Microphone.pdf](https://github.com/jsalt2019-diadet/jsalt2019-diadet.github.io/files/3321413/JSALT.Summer.School._.Speaker.Detection.in.Adverse.Scenarios.with.a.Single.Microphone.pdf)

I just printed the webpage as PDF if you want to preview it!

**Comment by hbredin** [comment]
Looks good to me. Thanks for providing the PDF preview.

**Pull request merged**
